export const BILLS_ALL_REQUEST = "BILLS_ALL_REQUEST";
export const BILLS_ALL_SUCCESS = "BILLS_ALL_SUCCESS";
export const BILLS_ALL_FAIL = "BILLS_ALL_FAIL";

export const MY_BILLS_REQUEST = "MY_BILLS_REQUEST";
export const MY_BILLS_SUCCESS = "MY_BILLS_SUCCESS";
export const MY_BILLS_FAIL = "MY_BILLS_FAIL";

export const BILLS_CREATE_REQUEST = "BILLS_CREATE_REQUEST";
export const BILLS_CREATE_SUCCESS = "BILLS_CREATE_SUCCESS";
export const BILLS_CREATE_FAIL = "BILLS_CREATE_FAIL";
//go to reducer

export const BILL_ID_REQUEST = "BILL_ID_REQUEST";
export const BILL_ID_SUCCESS = "BILL_ID_SUCCESS";
export const BILL_ID_FAIL = "BILL_ID_FAIL";

export const BILL_STATUS_REQUEST = "BILL_STATUS_REQUEST";
export const BILL_STATUS_SUCCESS = "BILL_STATUS_SUCCESS";
export const BILL_STATUS_FAIL = "BILL_STATUS_FAIL";
