export const POSTS_ALL_REQUEST = "POSTS_ALL_REQUEST";
export const POSTS_ALL_SUCCESS = "POSTS_ALL_SUCCESS";
export const POSTS_ALL_FAIL = "POSTS_ALL_FAIL";

export const POSTS_LIST_REQUEST = "POSTS_LIST_REQUEST";
export const POSTS_LIST_SUCCESS = "POSTS_LIST_SUCCESS";
export const POSTS_LIST_FAIL = "POSTS_LIST_FAIL";
//go to reducer

export const POSTS_BYCODE_REQUEST = "POSTS_BYCODE_REQUEST";
export const POSTS_BYCODE_SUCCESS = "POSTS_BYCODE_SUCCESS";
export const POSTS_BYCODE_FAILED = "POSTS_BYCODE_FAILED";

export const POSTS_CREATE_REQUEST = "POSTS_CREATE_REQUEST";
export const POSTS_CREATE_SUCCESS = "POSTS_CREATE_SUCCESS";
export const POSTS_CREATE_FAIL = "POSTS_CREATE_FAIL";

export const POSTS_UPDATE_REQUEST = "POSTS_UPDATE_REQUEST";
export const POSTS_UPDATE_SUCCESS = "POSTS_UPDATE_SUCCESS";
export const POSTS_UPDATE_FAIL = "POSTS_UPDATE_FAIL";

export const POSTS_UPDATESEAT_REQUEST = "POSTS_UPDATESEAT_REQUEST";
export const POSTS_UPDATESEAT_SUCCESS = "POSTS_UPDATESEAT_SUCCESS";
export const POSTS_UPDATESEAT_FAILED = "POSTS_UPDATESEAT_FAILED";

export const POSTS_UPDATESALE_REQUEST = "POSTS_UPDATESALE_REQUEST";
export const POSTS_UPDATESALE_SUCCESS = "POSTS_UPDATESALE_SUCCESS";
export const POSTS_UPDATESALE_FAILED = "POSTS_UPDATESALE_FAILED";

export const POSTS_UPDATEHIGHLIGHT_REQUEST = "POSTS_UPDATEHIGHLIGHT_REQUEST";
export const POSTS_UPDATEHIGHLIGHT_SUCCESS = "POSTS_UPDATEHIGHLIGHT_SUCCESS";
export const POSTS_UPDATEHIGHLIGHT_FAILED = "POSTS_UPDATEHIGHLIGHT_FAILED";

export const POSTS_DELETE_REQUEST = "POSTS_DELETE_REQUEST";
export const POSTS_DELETE_SUCCESS = "POSTS_DELETE_SUCCESS";
export const POSTS_DELETE_FAIL = "POSTS_DELETE_FAIL";
