export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";
//go to reducers

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_ALL_REQUEST = "USER_ALL_REQUEST";
export const USER_ALL_SUCCESS = "USER_ALL_SUCCESS";
export const USER_ALL_FAIL = "USER_ALL_FAIL";

export const USER_SINGLE_REQUEST = "USER_SINGLE_REQUEST";
export const USER_SINGLE_SUCCESS = "USER_SINGLE_SUCCESS";
export const USER_SINGLE_FAIL = "USER_SINGLE_FAIL";
